config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}

  root to: 'home#index'

  resources :expenses, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :reports, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :tags, only: [:index, :edit, :update, :new, :create, :destroy]

  get 'reports/remove_expense_from_report/:report_id/:expense_id', :to => 'reports#remove_expense_from_report'

  get 'expense/handle_images_get', :to => 'expenses#handle_images_get'
  post 'expense/handle_images_post', :to => 'expenses#handle_images_post'

end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :title, presence: true, length: { minimum: 1, maximum: 500}

    belongs_to :user
    has_and_belongs_to_many :expenses
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :authenticate_user!

    def index
  
      if current_user
        @tags = Tag.where(user_id: current_user.id)
      end
    end
  
    def edit
  
      @button_text = "Update"
      @tag = Tag.find(params[:id])
  
    end
  
    def update
  
      @tag = Tag.find(params[:id])
  
      if @tag.update_attributes(tag_params)
        redirect_to action: 'index'
      else
        render 'edit'
      end
  
    end
  
    def new
  
      @button_text = "Create"
      @tag = Tag.new
  
    end
  
    def create
  
      @tag = Tag.new(tag_params)
  
      if current_user
        @tag.user_id = current_user.id
      else
        render 'new'
      end
  
      if @tag.save
        redirect_to action: 'index'
      else
        render 'new'
      end
  
    end
  
    def destroy
  
      @tag = Tag.find(params[:id])
      @tag.destroy
  
      flash[:success] = "Tag deleted!"
    
      redirect_to tags_path
  
    end
  
    private
  
      def tag_params
        params.require(:tag).permit(:title, :description, :ammount,
                                        :tag_date, :currency)
      end
  end
  

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_error_messages.html.erb
<% if @tag.errors.any? %>
  <script>

      $(function () {
          toastr.options = {"timeOut": "5000"};

          <% @tag.errors.full_messages.each do |msg| %>
          toastr.error('<%= msg %>');
          <% end %>

          toastr.error('<%= t('errors', :count => @tag.errors.count) %>');
      });

  </script>
<% end %>

app/views/tags/_form.html.erb
<%= form_for(@tag,class: "justify-content-center") do |f| %>
  <%= render 'error_messages', object: @tag %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', required: true, minlength: 1, maxlength: 500 %>
    </div>
  
    <%= f.submit @button_text, class: "btn btn-block btn-primary" %>
  <% end %>
  

app/views/tags/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Add new tag</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/tags/index.html.erb
<%= render 'layouts/fuse' %>

<main>
  <div id="wrapper">

    <%= render 'layouts/sidebar' %>

    <div class="content-wrapper">

      <%= render 'layouts/navbar' %>

      <div class="content custom-scrollbar">
        <div class="page-layout blank p-6">
          <div class="jumbotron jumbotron-title">
            <h2 class="display-4"><%= t('tags.your_tags') %>></h2>
          </div>
          <div class="custom-table-container">
            </br>
            <div class="text-center">

              <%= link_to new_tag_path(@tag), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: "btn btn-info"} do %>
                <i class="fas fa-plus-circle"></i> <%= t('tags.add_new_tag') %>
              <% end %>

            </div>

            <% if @tags.length > 0 %>

              <% @tags.each do |tag| %>

                <div class="div_custom">
                  <a href="#" class="tag"><span><%= tag.title %></span></a>
                  <%= link_to tag_path(tag), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </div>

              <% end %>

            <% else %>

              <div class="p-3 no-expenses-msg">
                <section id="warning">
                  <section class="warningContent">
                    <span>!</span>
                    <h5 class="wHeading"><%= t('general.we_are_sorry') %></h5>
                    <p><%= t('tags.no_tags') %></p>
                  </section>
                </section>
              </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
</main>

app/views/tags/new.html.erb
<div class="jumbotron jumbotron-title">
  <h2 class="display-4">Add New Tag</h2>
</div>

</br>
</br>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <%= render 'form' %>
    </div>
  </div>
</div>

</br>
</br>

app/views/tags/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");

$("#modal-window").modal();