config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}

  root to: 'home#index'

  resources :expenses, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :reports, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :tags, only: [:index, :edit, :update, :new, :create, :destroy]

  get 'reports/remove_expense_from_report/:report_id/:expense_id', :to => 'reports#remove_expense_from_report'

  get 'expense/handle_images_get', :to => 'expenses#handle_images_get'
  post 'expense/handle_images_post', :to => 'expenses#handle_images_post'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         # :confirmable, :trackable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2, :twitter]

  has_many :expenses
  has_many :reports
  has_many :tags

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.skip_confirmation!
    end
  end

  def self.from_omniauth(auth, signed_in_resource = nil)

    user = User.where(provider: auth.provider, uid: auth.uid).first
    if user.present?
      user
    else
      # Check user with the same email address
      user_with_email = User.find_by_email(auth.info.email)
      if user_with_email.present?
        user = user_with_email
      else
        user = User.new
        if auth.provider == "facebook"

          user.provider = auth.provider
          user.uid = auth.uid
          user.email = auth.extra.raw_info.email

          user.save

        elsif auth.provider == "twitter"

          user.provider = auth.provider
          user.uid = auth.uid

        elsif auth.provider == "google_oauth2"

          user.provider = auth.provider
          user.uid = auth.uid
          user.email = auth.info.email

          user.save

        end
      end
    end

    user

  end

  # For Twitter (save the session eventhough we redirect user to registration page first)
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  # For Twitter (disable password validation)
  def password_required?
    super && provider.blank?
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user
      @expenses = Expense.where(user_id: current_user.id)
    end
  end

  def show
    @expense = Expense.find(params[:id])
    @expense.tags.build

    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @button_text = "Update"
    @expense = Expense.find(params[:id])
    @tags = {}
    Tag.all.collect {|t| @tags[t.title] = t.id }

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @expense = Expense.find(params[:id])

    handle_tags_for_expense
    
    if @expense.update_attributes(expense_params)

      flash[:success] = "Expense updated!"
      redirect_to action: 'index'

    else

      flash[:error] = "Expense update failed!"
      render 'edit'

    end
  end

  def new
    @button_text = "Create"
    @expense = Expense.new
    @tags = {}
    Tag.all.collect {|t| @tags[t.title] = t.id }
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    if current_user
      @expense = Expense.new(expense_params)
      @expense.user_id = current_user.id
      handle_tags_for_expense
      if @expense.save

        flash[:success] = "Expense created!"
        redirect_to action: 'index'

      else

        flash[:error] = "Expense create failed!"
        render 'new'

      end

    else
      flash[:error] = "Expense create failed!"
      render 'new'
    end

  end

  def handle_images_get
    @button_text = "Upload"
    @expense = Expense.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def handle_images_post
    abort('De aici trebuie luate pozele!')
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    flash[:success] = "Expense deleted!"

    redirect_to expenses_path
  end

  private

    def expense_params
      params.require(:expense).permit(:title, :description, :amount, :expense_date, :currency)
    end

    def handle_tags_for_expense
      if params['tag_ids']
        @expense.tags.clear
        tags = params['tag_ids'].map { |id| Tag.find(id) }
        @expense.tags << tags 
    end 

end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_edit.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= t('expenses.edit_expense') %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/_error_messages.html.erb
<% if @expense.errors.any? %>
  <script>

      $(function () {
          toastr.options = {"timeOut": "5000"};

          <% @expense.errors.full_messages.each do |msg| %>
          toastr.error('<%= msg %>');
          <% end %>

          toastr.error('<%= t('errors', :count => @expense.errors.count) %>');
      });

  </script>
<% end %>

app/views/expenses/_form.html.erb
<%= form_for(@expense, class: "justify-content-center") do |f| %>
  <%= render 'error_messages', object: @expense %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true, minlength: 1, maxlength: 500 %>
  </div>

  <div class="form-group">
    <labeL>Tags</label>

    <%= select_tag("tag_ids[]",
                   options_for_select(Tag.all.collect {|tag| [tag.title, tag.id]}, @expense.tags.collect {|tag| tag.id}),
                   {:multiple => true, :class => "form-control", "data-style" => "btn-primary"}) %>

  </div>
  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, class: 'form-control', step: :any, required: true, min: 0 %>
  </div>

  <div class="form-group">
    <%= f.label :currency %>
    <%= f.collection_select :currency, Expense.currencies.to_a.map {|w| [w[0], w[0].humanize.upcase]},
                            :first, :second, {}, {:class => 'form-control', "data-style" => "btn-primary"} %>
  </div>

  <div class="form-group">
    <%= f.label :expense_date %>
    <%= f.date_field :expense_date, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', maxlength: 2000 %>
  </div>

  <%= f.submit @button_text, class: "btn btn-block btn-primary" %>
<% end %>

app/views/expenses/_handle_images_get.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= t('expenses.upload_images') %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <%= render 'images_form' %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/_images_form.html.erb
<%= form_for(@expense, :url => {:action => "handle_images_post"}, class: "justify-content-center") do |f| %>
  <%= render 'error_messages', object: @expense %>

  <div class="form-group">
    <%= f.label :images %>
    <%= f.file_field :images, class: 'form-control', accept: 'image/*', multiple: true, required: true %>
  </div>

  <%= f.submit @button_text, class: "btn btn-block btn-primary" %>
<% end %>

app/views/expenses/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= t('expenses.add_new_expense') %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/_show.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= t('expenses.view_expense') %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @expense.title %></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class=" col-md-12 col-lg-12 ">
                <table class="table table-user-information">
                  <tbody>
                  <tr>
                    <td><%= t('expenses.amount') %></td>
                    <td><%= @expense.amount.to_s + ' ' + @expense.currency.to_s.humanize.upcase %></td>
                  </tr>
                  <tr>
                    <td><%= t('expenses.expense_date') %></td>
                    <td><%= @expense.expense_date %></td>
                  </tr>
                  <tr>
                    <td><%= t('expenses.description') %></td>
                    <td><%= @expense.description %></td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/expenses/edit.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
  <style>
    ::-webkit-scrollbar {
      width: 5px;
    }

    ::-webkit-scrollbar-track {
      background: #f1f1f1;
    }

    ::-webkit-scrollbar-thumb {
      background: #888;
    }

    ::-webkit-scrollbar-thumb:hover {
      background: #555;
    }
  </style>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('expenses.edit_expense') %></h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <%= render 'form' %>
    </div>
  </div>
</div>

</br>
</br>

app/views/expenses/handle_images_get.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('expenses.upload_images') %></h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <%= render 'images_form' %>
    </div>
  </div>
</div>

</br>
</br>

app/views/expenses/handle_images_get.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'handle_images_get') %>");
$("#modal-window").modal();

app/views/expenses/index.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<%= render 'layouts/fuse' %>

<main>

  <div id="wrapper">

    <%= render 'layouts/sidebar' %>

    <div class="content-wrapper">

      <%= render 'layouts/navbar' %>

      <div class="content custom-scrollbar">
        <div class="page-layout blank p-6">
          <div class="jumbotron jumbotron-title">
            <h2 class="display-4"><%= t('expenses.your_expenses') %></h2>
          </div>
          <div class="custom-table-container">
            </br>
            <div class="text-center">

              <%= link_to new_expense_path(@expense), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: "btn btn-info"} do %>
                <i class="fas fa-plus-circle"></i> <%= t('expenses.add_new_expense') %>
              <% end %>

              <%= link_to expense_handle_images_get_path(@expense), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: "btn btn-info"} do %>
                <i class="fas fa-file-upload"></i> <%= t('expenses.upload_images') %>
              <% end %>

            </div>

            <% if @expenses.length > 0 %>

              <table id="expenses_table" class="container table table-hover">
                <thead>
                <tr>
                  <th><h1><%= t('expenses.title') %></h1></th>
                  <th><h1><%= t('expenses.amount') %></h1></th>
                  <th><h1><%= t('expenses.expense_date') %></h1></th>
                  <th><h1><%= t('expenses.description') %></h1></th>
                  <th><h1><%= t('expenses.tags') %></h1></th>
                  <th class="text-center w-25"><h1><%= t('expenses.actions') %></h1></th>
                </tr>
                </thead>
                <tbody>

                <% @expenses.each do |expense| %>

                  <tr>
                    <td><%= link_to expense.title, expense_path(expense), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window'} %></td>
                    <td><%= expense.amount.to_s + ' ' + expense.currency.to_s.humanize.upcase %></td>
                    <td><%= expense.expense_date %></td>
                    <td><%= expense.description %></td>
                    <td>
                      <% expense.tags.each do |tag| %>
                        <span> | <%= tag.title %> | </span>
                      <% end %>
                    </td>
                    <td class="text-center w-25">

                      <%= link_to edit_expense_path(expense), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: "btn btn-info"} do %>
                        <i class="fas fa-edit"></i>
                      <% end %>

                      <%= link_to expense_path(expense), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>

                    </td>
                  </tr>

                <% end %>

                </tbody>
              </table>

            <% else %>

              <div class="p-3 no-expenses-msg">
                <section id="warning">
                  <section class="warningContent">
                    <span>!</span>
                    <h5 class="wHeading"><%= t('general.we_are_sorry') %></h5>
                    <p><%= t('expenses.no_expenses') %></p>
                  </section>
                </section>
              </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
</main>

<script type="text/javascript">

    <% if @expenses.length > 0 %>
    $(document).ready(function () {
        $('#expenses_table').DataTable();
    });
    <% end %>

    <% if flash[:success] != nil %>
    $(function () {
        toastr.success('<%= flash[:success] %>');
    });
    <% end %>

    <% if flash[:error] != nil %>
    $(function () {
        toastr.error('<%= flash[:error] %>');
    });
    <% end %>

</script>

app/views/expenses/new.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
  <style>
    ::-webkit-scrollbar {
      width: 5px;
    }

    ::-webkit-scrollbar-track {
      background: #f1f1f1;
    }

    ::-webkit-scrollbar-thumb {
      background: #888;
    }

    ::-webkit-scrollbar-thumb:hover {
      background: #555;
    }
  </style>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('expenses.add_new_expense') %></h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <%= render 'form' %>
    </div>
  </div>
</div>

</br>
</br>

app/views/expenses/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/expenses/show.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
  <style>
    ::-webkit-scrollbar {
      width: 5px;
    }

    ::-webkit-scrollbar-track {
      background: #f1f1f1;
    }

    ::-webkit-scrollbar-thumb {
      background: #888;
    }

    ::-webkit-scrollbar-thumb:hover {
      background: #555;
    }
  </style>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('expenses.view_expense') %></h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @expense.title %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class=" col-md-12 col-lg-12 ">
              <table class="table table-user-information">
                <tbody>
                <tr>
                  <td><%= t('expenses.amount') %></td>
                  <td><%= @expense.amount.to_s + ' ' + @expense.currency.to_s.humanize.upcase %></td>
                </tr>
                <tr>
                  <td><%= t('expenses.expense_date') %></td>
                  <td><%= @expense.expense_date %></td>
                </tr>
                <tr>
                  <td><%= t('expenses.description') %></td>
                  <td><%= @expense.description %></td>
                </tr>
                </tbody>
              </table>

              <%= link_to "Back to My Expenses", action: "index", class: "btn btn-primary" %>

            </div>
          </div>
        </div>
        <div class="panel-footer">

          <%= link_to edit_expense_path(@expense), class: "btn btn-info" do %>
            <i class="fas fa-edit"></i>
          <% end %>

          <span class="pull-right">

            <%= link_to expense_path(@expense), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" do %>
                  <i class="fas fa-trash-alt"></i>
            <% end %>

          </span>
        </div>
      </div>
    </div>
  </div>
</div>

<style>

  .user-row {
    margin-bottom: 14px;
  }

  .user-row:last-child {
    margin-bottom: 0;
  }

  .dropdown-user {
    margin: 13px 0;
    padding: 5px;
    height: 100%;
  }

  .dropdown-user:hover {
    cursor: pointer;
  }

  .table-user-information > tbody > tr {
    border-top: 1px solid rgb(221, 221, 221);
  }

  .table-user-information > tbody > tr:first-child {
    border-top: 0;
  }


  .table-user-information > tbody > tr > td {
    border-top: 0;
  }

  .toppad {
    margin-top: 20px;
  }

</style>

<script type="text/javascript">

    $(document).ready(function () {
        var panels = $('.user-infos');
        var panelsButton = $('.dropdown-user');
        panels.hide();

        //Click dropdown
        panelsButton.click(function () {
            //get data-for attribute
            var dataFor = $(this).attr('data-for');
            var idFor = $(dataFor);

            //current button
            var currentButton = $(this);
            idFor.slideToggle(400, function () {
                //Completed slidetoggle
                if (idFor.is(':visible')) {
                    currentButton.html('<i class="glyphicon glyphicon-chevron-up text-muted"></i>');
                } else {
                    currentButton.html('<i class="glyphicon glyphicon-chevron-down text-muted"></i>');
                }
            })
        });


        $('[data-toggle="tooltip"]').tooltip();

        $('button').click(function (e) {
            e.preventDefault();
            alert("This is a demo.\n :-)");
        });
    });

</script>