config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}

  root to: 'home#index'

  resources :expenses, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :reports, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :tags, only: [:index, :edit, :update, :new, :create, :destroy]

  get 'reports/remove_expense_from_report/:report_id/:expense_id', :to => 'reports#remove_expense_from_report'

  get 'expense/handle_images_get', :to => 'expenses#handle_images_get'
  post 'expense/handle_images_post', :to => 'expenses#handle_images_post'

end

app/models/report.rb
class Report < ApplicationRecord

  enum currency: [:ron, :euro, :usd]

  validates :title, presence: true, length: {minimum: 1, maximum: 500}
  validates :from_date, presence: true
  validates :to_date, presence: true
  validates :from_date, date: {before_or_equal_to: :to_date}
  validates :description, length: {maximum: 2000}

  belongs_to :user
  has_and_belongs_to_many :expenses

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user
      @reports = Report.where(user_id: current_user.id)
    end
  end

  def show
    @report = Report.includes(:expenses).find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @button_text = "Update"
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @report = Report.find(params[:id])

    if @report.update_attributes(expense_params)

      flash[:success] = "Report updated!"
      redirect_to action: 'index'

    else

      flash[:error] = "Report update failed!"
      render 'edit'

    end
  end

  def new
    @button_text = "Create"
    @report = Report.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create

    @report = Report.new(expense_params)

    if current_user
      @report.user_id = current_user.id
    else
      render 'new'
    end

    if @report.save
      expenses = Expense.where(expense_date: @report.from_date..@report.to_date, user_id: current_user.id)

      if expenses.any?
        expenses.each do |expense|
          @report.expenses << expense
        end
      end

      flash[:success] = "Report created!"
      redirect_to action: 'index'

    else

      flash[:error] = "Report create failed!"
      render 'new'

    end

  end

  def destroy

    @report = Report.find(params[:id])
    @report.destroy

    flash[:success] = "Report deleted!"

    redirect_to reports_path

  end

  def remove_expense_from_report

    @report = Report.find(params[:report_id])

    if @report
      @expense = Expense.find(params[:expense_id])

      if @expense
        @report.expenses.delete(@expense)

        redirect_to action: "show", id: @report.id
      end
    end

  end

  private

  def expense_params
    params.require(:report).permit(:title, :from_date, :to_date, :description, :currency, :target_id)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_edit.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= t('reports.edit_report') %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/reports/_error_messages.html.erb
<% if @report.errors.any? %>
  <script>

      $(function () {
          toastr.options = {"timeOut": "5000"};

          <% @report.errors.full_messages.each do |msg| %>
          toastr.error('<%= msg %>');
          <% end %>

          toastr.error('<%= t('errors', :count => @report.errors.count) %>');
      });

  </script>
<% end %>

app/views/reports/_form.html.erb
<%= form_for(@report, class: "justify-content-center") do |f| %>
  <%= render 'error_messages', object: @report %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', required: true, minlength: 1, maxlength: 500 %>
  </div>

  <div class="form-group">
    <%= f.label :from_date %>
    <%= f.date_field :from_date, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :to_date %>
    <%= f.date_field :to_date, class: 'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.label :currency %>
    <%= f.collection_select :currency, Report.currencies.to_a.map {|w| [w[0], w[0].humanize.upcase]}, :first, :second, {}, {:class => 'form-control', "data-style" => "btn-primary"} %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', maxlength: 2000 %>
  </div>

  <%= f.submit @button_text, class: "btn btn-block btn-primary" %>
<% end %>

app/views/reports/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= t('reports.add_new_report') %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/reports/_show.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel"><%= t('reports.view_report') %></h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @report.title %></h3>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class=" col-md-12 col-lg-12 ">
                <table class="table table-user-information">
                  <tbody>
                  <tr>
                    <td><%= t('reports.from_date') %></td>
                    <td><%= @report.from_date %></td>
                  </tr>
                  <tr>
                    <td><%= t('reports.to_date') %></td>
                    <td><%= @report.to_date %></td>
                  </tr>
                  <tr>
                    <td><%= t('reports.currency') %></td>
                    <td><%= @report.currency.to_s.humanize.upcase %></td>
                  </tr>
                  <tr>
                    <td><%= t('reports.description') %></td>
                    <td><%= @report.description %></td>
                  </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/edit.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
  <style>
    ::-webkit-scrollbar {
      width: 5px;
    }

    ::-webkit-scrollbar-track {
      background: #f1f1f1;
    }

    ::-webkit-scrollbar-thumb {
      background: #888;
    }

    ::-webkit-scrollbar-thumb:hover {
      background: #555;
    }
  </style>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('reports.edit_report') %></h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <%= render 'form' %>
    </div>
  </div>
</div>

</br>
</br>

app/views/reports/edit.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-window").modal();

app/views/reports/index.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<%= render 'layouts/fuse' %>

<main>

  <div id="wrapper">

    <%= render 'layouts/sidebar' %>

    <div class="content-wrapper">

      <%= render 'layouts/navbar' %>

      <div class="content custom-scrollbar">
        <div class="page-layout blank p-6">
          <div class="jumbotron jumbotron-title">
            <h2 class="display-4">Your Reports</h2>
          </div>

          <div class="custom-table-container">
            </br>

            <div class="text-center">

              <%= link_to new_report_path(@report), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: "btn btn-info"} do %>
                <i class="fas fa-plus-circle"></i> <%= t('reports.add_new_report') %>
              <% end %>

            </div>

            <% if @reports.length > 0 %>

              <table id="reports_table" class="container table table-hover">
                <thead>
                <tr>
                  <th><h1><%= t('reports.title') %></h1></th>
                  <th><h1><%= t('reports.from_date') %></h1></th>
                  <th><h1><%= t('reports.to_date') %></h1></th>
                  <th><h1><%= t('reports.description') %></h1></th>
                  <th class="text-center w-25"><h1><%= t('reports.actions') %></h1></th>
                </tr>
                </thead>
                <tbody>

                <% @reports.each do |report| %>

                  <tr>
                    <td><%= link_to report.title, report_path(report), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window'} %></td>
                    <td><%= report.from_date %></td>
                    <td><%= report.to_date %></td>
                    <td><%= report.description %></td>
                    <td class="text-center w-25">

                      <%= link_to edit_report_path(report), {:remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window', class: "btn btn-info"} do %>
                        <i class="fas fa-edit"></i>
                      <% end %>

                      <%= link_to report_path(report), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" do %>
                        <i class="fas fa-trash-alt"></i>
                      <% end %>

                    </td>
                  </tr>

                <% end %>

                </tbody>
              </table>

            <% else %>

              <div class="p-3 no-expenses-msg">
                <section id="warning">
                  <section class="warningContent">
                    <span>!</span>
                    <h5 class="wHeading"><%= t('general.we_are_sorry') %></h5>
                    <p><%= t('reports.no_reports') %></p>
                  </section>
                </section>
              </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
</main>

<script type="text/javascript">

    <% if @reports.length > 0 %>
    $(document).ready(function () {
        $('#reports_table').DataTable({
            columnDefs: [{
                targets: [4]
            }]
        });
    });
    <% end %>

    <% if flash[:success] != nil %>
    $(function () {
        toastr.success('<%= flash[:success] %>');
    });
    <% end %>

    <% if flash[:error] != nil %>
    $(function () {
        toastr.error('<%= flash[:error] %>');
    });
    <% end %>

</script>

app/views/reports/new.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
  <style>
    ::-webkit-scrollbar {
      width: 5px;
    }

    ::-webkit-scrollbar-track {
      background: #f1f1f1;
    }

    ::-webkit-scrollbar-thumb {
      background: #888;
    }

    ::-webkit-scrollbar-thumb:hover {
      background: #555;
    }
  </style>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('reports.add_new_report') %></h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <%= render 'form' %>
    </div>
  </div>
</div>

</br>
</br>

app/views/reports/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

$('#report_from_date').on('change', function () {
    $('#report_to_date').attr('min', $(this).val());
});

$('#report_to_date').on('change', function () {
    $('#report_from_date').attr('max', $(this).val());
});

app/views/reports/show.html.erb
<%= content_for :stylesheets do %>
  <link rel="stylesheet" type="text/css"
        href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"
        media="all" data-turbolinks-track="reload"/>
  <style>
    ::-webkit-scrollbar {
      width: 5px;
    }

    ::-webkit-scrollbar-track {
      background: #f1f1f1;
    }

    ::-webkit-scrollbar-thumb {
      background: #888;
    }

    ::-webkit-scrollbar-thumb:hover {
      background: #555;
    }
  </style>
<% end %>

<%= content_for :scripts do %>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"
          media="all" data-turbolinks-track="reload" defer></script>
<% end %>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('reports.view_report') %></h2>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 toppad">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @report.title %></h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class=" col-md-12 col-lg-12 ">
              <table class="table table-user-information">
                <tbody>
                <tr>
                  <td><%= t('reports.from_date') %></td>
                  <td><%= @report.from_date %></td>
                </tr>
                <tr>
                  <td><%= t('reports.to_date') %></td>
                  <td><%= @report.to_date %></td>
                </tr>
                <tr>
                  <td><%= t('reports.currency') %></td>
                  <td><%= @report.currency.to_s.humanize.upcase %></td>
                </tr>
                <tr>
                  <td><%= t('reports.description') %></td>
                  <td><%= @report.description %></td>
                </tr>
                </tbody>
              </table>

              <%= link_to "Back to My Reports", action: "index", class: "btn btn-primary" %>

            </div>
          </div>
        </div>
        <div class="panel-footer">

          <%= link_to edit_report_path(@report), class: "btn btn-info" do %>
            <i class="fas fa-edit"></i>
          <% end %>

          <span class="pull-right">

            <%= link_to report_path(@report), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>

          </span>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <h3>Pie chart</h3>
  <%= pie_chart @report.expenses.group(:currency).count %>
</div>

<div class="container">
  <h3>Bar chart</h3>
  <%= bar_chart @report.expenses.group(:amount).count %>
</div>

<div class="container">
  <h3>Line chart</h3>
  <%= line_chart @report.expenses.group_by_day(:expense_date, format: "%B %d, %Y").count, discrete: true %>
</div>

<div class="jumbotron jumbotron-title">
  <h2 class="display-4"><%= t('reports.expenses') %></h2>
</div>

<div class="table-container">
  <table id="expenses_table" class="container">
    <thead>
    <tr>
      <th><h1><%= t('expenses.title') %></h1></th>
      <th><h1><%= t('expenses.amount') %></h1></th>
      <th><h1><%= t('expenses.expense_date') %></h1></th>
      <th><h1><%= t('expenses.description') %></h1></th>
      <th><h1><%= t('expenses.actions') %></h1></th>
    </tr>
    </thead>
    <tbody>

    <% @report.expenses.each do |expense| %>

      <tr>
        <td><%= link_to expense.title, expense_path(expense) %></td>
        <td><%= expense.amount %></td>
        <td><%= expense.expense_date %></td>
        <td><%= expense.description %></td>
        <td>

          <%= link_to :action => "remove_expense_from_report",
                      :report_id => @report.id,
                      :expense_id => expense.id,
                      data: {confirm: 'Are you sure?'},
                      class: "btn btn-danger" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>

        </td>
      </tr>

    <% end %>

    </tbody>
  </table>
</div>


<script type="text/javascript">

    $(document).ready(function () {
        $('#expenses_table').DataTable();
    });

</script>

<style>

  .user-row {
    margin-bottom: 14px;
  }

  .user-row:last-child {
    margin-bottom: 0;
  }

  .dropdown-user {
    margin: 13px 0;
    padding: 5px;
    height: 100%;
  }

  .dropdown-user:hover {
    cursor: pointer;
  }

  .table-user-information > tbody > tr {
    border-top: 1px solid rgb(221, 221, 221);
  }

  .table-user-information > tbody > tr:first-child {
    border-top: 0;
  }

  .table-user-information > tbody > tr > td {
    border-top: 0;
  }

  .toppad {
    margin-top: 20px;
  }

  @charset "UTF-8";
  @import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,700);

  .table-container {
    font-family: 'Open Sans', sans-serif;
    font-weight: 300;
    line-height: 1.42em;
    color: #A7A1AE;
    background-color: #1F2739;
    padding-bottom: 30px;
  }

  .table-container h1 {
    font-size: 3em;
    font-weight: 300;
    line-height: 1em;
    text-align: center;
    color: #4DC3FA;
  }

  .table-container h2 {
    font-size: 1em;
    font-weight: 300;
    text-align: center;
    display: block;
    line-height: 1em;
    padding-bottom: 2em;
    color: #FB667A;
  }

  .table-container h2 a {
    font-weight: 700;
    text-transform: uppercase;
    color: #FB667A;
    text-decoration: none;
  }

  .table-container .blue {
    color: #185875;
  }

  .table-container .yellow {
    color: #FFF842;
  }

  .table-container .container th h1 {
    font-weight: bold;
    font-size: 1em;
    text-align: left;
    color: #185875;
  }

  .table-container .container td {
    font-weight: normal;
    font-size: 1em;
    -webkit-box-shadow: 0 2px 2px -2px #0E1119;
    -moz-box-shadow: 0 2px 2px -2px #0E1119;
    box-shadow: 0 2px 2px -2px #0E1119;
  }

  .table-container .container {
    text-align: left;
    overflow: hidden;
    width: 80%;
    margin: 0 auto;
    display: table;
    padding: 0 0 8em 0;
  }

  .table-container .container td, .container th {
    padding-bottom: 2%;
    padding-top: 2%;
    padding-left: 2%;
  }

  /* Background-color of the odd rows */
  .table-container .container tr:nth-child(odd) {
    background-color: #323C50;
  }

  /* Background-color of the even rows */
  .table-container .container tr:nth-child(even) {
    background-color: #2C3446;
  }

  .table-container .container th {
    background-color: #1F2739;
  }

  .table-container .container td:first-child {
    color: #FB667A;
  }

  .table-container .container tr:hover {
    background-color: #464A52;
    -webkit-box-shadow: 0 6px 6px -6px #0E1119;
    -moz-box-shadow: 0 6px 6px -6px #0E1119;
    box-shadow: 0 6px 6px -6px #0E1119;
  }

  .table-container .container td:hover {
    background-color: #FFF842;
    color: #403E10;
    font-weight: bold;

    box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;
    transform: translate3d(6px, -6px, 0);

    transition-delay: 0s;
    transition-duration: 0.4s;
    transition-property: all;
    transition-timing-function: line;
  }

  @media (max-width: 800px) {
    .table-container .container td:nth-child(4),
    .table-container .container th:nth-child(4) {
      display: none;
    }
  }

  .jumbotron {
    margin-bottom: 0 !important;
  }

</style>

app/views/reports/show.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'show') %>");
$("#modal-window").modal();