config/routes.rb
Rails.application.routes.draw do

  get 'dashboard/index'

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}

  root to: 'home#index'

  resources :expenses, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :reports, only: [:index, :show, :edit, :update, :new, :create, :destroy]

  resources :tags, only: [:index, :edit, :update, :new, :create, :destroy]

  get 'reports/remove_expense_from_report/:report_id/:expense_id', :to => 'reports#remove_expense_from_report'

  get 'expense/handle_images_get', :to => 'expenses#handle_images_get'
  post 'expense/handle_images_post', :to => 'expenses#handle_images_post'

end

app/views/layouts/_features.html.erb
<div class="features-boxed">
  <div class="container">
    <div class="intro">
      <h2 class="text-center"><%= t('home.features') %></h2>
    </div>
    <div class="row justify-content-centerfeatures">
      <div class="col-sm-6 col-md-5 col-lg-4 item">
        <div class="box"><i class="fa fa-tablet-alt icon"></i> <i class="fa fa-mobile-alt icon"></i> <i class="fa fa-desktop icon"></i>
          <h3 class="name"><%= t('home.works_on_everything') %></h3>
          <p class="description"><%= t('home.works_on_everything_text') %></p></div>
      </div>
      <div class="col-sm-6 col-md-5 col-lg-4 item">
        <div class="box"><i class="fa fa-clock icon"></i>
          <h3 class="name"><%= t('home.always_available') %></h3>
          <p class="description"><%= t('home.always_available_text') %></p></div>
      </div>
      <div class="col-sm-6 col-md-5 col-lg-4 item">
        <div class="box"><i class="fa fa-globe icon"></i>
          <h3 class="name"><%= t('home.international') %></h3>
          <p class="description"><%= t('home.international_text') %></p></div>
      </div>
      <div class="col-sm-6 col-md-5 col-lg-4 item">
        <div class="box"><i class="fa fa-list-alt icon"></i>
          <h3 class="name"><%= t('home.customizable') %></h3>
          <p class="description"><%= t('home.customizable_text') %></p></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer-dark" id="footer" style="position: relative;">
  <div class="container">
    <div id="footer">
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-3 item">
            </div>
            <div class="col-sm-6 col-md-3 item">
            </div>
            <div class="col-md-6 item text">
              <h3>
                <%= t('home.subscribe_to_newsletter') %>
              </h3>
              <form class="form-inline" method="post">
                <div class="form-group">
                  <input class="form-control" type="email" name="email" placeholder="Your Email"></div>
                <div class="form-group">
                  <button class="btn btn-primary" type="submit"><%= t('home.subscribe') %></button>
                </div>
              </form>
            </div>
          </div>
          <p class="copyright">SSS - Smart Spending & Savings © 2019</p>
        </div>
      </footer>
    </div>
  </div>
</div>

app/views/layouts/_fuse.html.erb
<%= content_for :stylesheets do %>
  <style type="text/css">
    [fuse-cloak],
    .fuse-cloak {
      display: none !important;
    }

    #toggle-fold-aside-button {
      display: none !important;
    }
  </style>

  <%= stylesheet_link_tag 'styles/dashboard', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'styles/table', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

<%= content_for :scripts do %>
  <%= javascript_include_tag 'dashboard/dashboard', :type => 'module', media: 'all', 'data-turbolinks-track': 'reload' %>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/jquery.perfect-scrollbar/1.4.0/perfect-scrollbar.min.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.2/d3.min.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.buttons.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.callbacks.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.mobile.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.history.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.desktop.js"
          media="all" data-turbolinks-track="reload"></script>

  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/pnotify/3.2.1/pnotify.confirm.js"
          media="all" data-turbolinks-track="reload"></script>

  <%= javascript_include_tag 'js/main', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/layouts/_header.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css"/>

<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">

        <% if user_signed_in? %>

          <li>
            <%= link_to "Home", dashboard_index_path %>
          </li>

        <% else %>

          <li>
            <%= link_to "Home", root_path %>
          </li>

        <% end %>

      </ul>

      <% if user_signed_in? %>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to('<i class="fas fa-sign-out-alt"></i> Sign Out'.html_safe, destroy_user_session_path, method: :delete, class: "navbar-brand navbar-right") %>
          </li>
        </ul>

      <% else %>

        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <b><%= t('home.log_in') %></b> <span class="caret"></span>
            </a>
            <ul id="login-dp" class="dropdown-menu">
              <li>
                <div class="row">
                  <div class="col-md-12">
                    <%= t('home.sign_in_with') %>
                    <div class="social-buttons">

                      <%= link_to omniauth_authorize_path(:user, :facebook), class: "btn btn-fb" do %>
                        <i class="fab fa-facebook"></i> Facebook
                      <% end %>

                      <%= link_to omniauth_authorize_path(:user, :twitter), class: "btn btn-twitter" do %>
                        <i class="fab fa-twitter-square"></i> Twitter
                      <% end %>

                      <%= link_to omniauth_authorize_path(:user, :google_oauth2), class: "btn btn-google" do %>
                        <i class="fab fa-google"></i> Google
                      <% end %>

                    </div>

                    <%= t('general.or') %>

                    <%= simple_form_for(:user, :url => session_path(:user), class: "form") do |f| %>
                      <%= f.error_notification %>

                      <div class="form-group">
                        <label class="sr-only" for="email">Email</label>
                        <%= f.input_field :email,
                                          required: false,
                                          autofocus: true,
                                          input_html: {autocomplete: "email"},
                                          class: "form-control field-with-errors",
                                          label: false %>
                      </div>
                      <div class="form-group">
                        <label class="sr-only" for="password"><%= t('home.password') %></label>
                        <%= f.input_field :password,
                                          required: false,
                                          input_html: {autocomplete: "current-password"},
                                          class: "form-control field-with-errors",
                                          label: false %>
                        <div class="help-block text-right">
                          <%= link_to t(".forgot_your_password"), new_password_path(:user) %><br/>
                        </div>
                      </div>

                      <div class="form-group">
                        <%= f.button :submit, t("home.log_in"), class: "btn btn-primary btn-block" %>
                      </div>
                      <div class="checkbox">
                        <label>
                          <%= f.input_field :remember_me,
                                            label: false,
                                            as: :boolean %>
                          <%= t('home.remember_me') %>
                        </label>
                      </div>

                    <% end %>

                  </div>

                  <div class="bottom text-center">
                    <%= t('home.new_here') %>
                    <%= link_to t('home.join'), controller: "devise/registrations", action: "new" %>
                  </div>

                </div>
              </li>
            </ul>
          </li>
        </ul>

      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<nav id="toolbar" class="bg-white">
  <div class="row no-gutters align-items-center flex-nowrap">
    <div class="col">
      <div class="row no-gutters align-items-center flex-nowrap">
        <button type="button" class="toggle-aside-button btn btn-icon d-block d-lg-none" data-fuse-bar-toggle="aside">
          <i class="icon icon-menu"></i>
        </button>
        <div class="toolbar-separator d-block d-lg-none"></div>
        <div class="shortcuts-wrapper row no-gutters align-items-center px-0 px-sm-2">
        </div>
      </div>
    </div>
    <div class="col-auto">
      <div class="row no-gutters align-items-center justify-content-end">
        <div class="user-menu-button dropdown">
          <div class="dropdown-toggle ripple row align-items-center no-gutters px-2 px-sm-4" role="button" id="dropdownUserMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="avatar-wrapper">
              <img class="avatar" src="../assets/images/avatars/profile.jpg">
              <i class="status text-green icon-checkbox-marked-circle s-4"></i>
            </div>
            <!--            <span id="usernameSpan" class="username mx-3 d-none d-md-block">John Doe</span>-->
          </div>

          <div class="dropdown-menu" aria-labelledby="dropdownUserMenu">

            <!--            <a class="dropdown-item" href="#">
                          <div class="row no-gutters align-items-center flex-nowrap">
                            <i class="icon-account"></i>
                            <span class="px-3">My Profile</span>
                          </div>
                        </a>

                        <a class="dropdown-item" href="#">
                          <div class="row no-gutters align-items-center flex-nowrap">
                            <i class="icon-email"></i>
                            <span class="px-3">Inbox</span>
                          </div>
                        </a>

                        <a class="dropdown-item" href="#">
                          <div class="row no-gutters align-items-center flex-nowrap">
                            <i class="status text-green icon-checkbox-marked-circle"></i>
                            <span class="px-3">Online</span>
                          </div>
                        </a>-->

            <!--            <div class="dropdown-divider"></div>-->

            <%= link_to destroy_user_session_path, method: :delete, :class => 'dropdown-item' do %>

              <div class="row no-gutters align-items-center flex-nowrap">
                <i class="icon-logout"></i>
                <span class="px-3">Logout</span>
              </div>

            <% end %>

          </div>
        </div>
        <div class="toolbar-separator"></div>
        <div class="language-button dropdown">
          <div class="dropdown-toggle ripple row align-items-center justify-content-center no-gutters px-0 px-sm-4" role="button" id="dropdownLanguageMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="row no-gutters align-items-center">
              <img class="flag mr-2" src="../assets/images/flags/us.png">
              <span class="d-none d-md-block">EN</span>
            </div>
          </div>
          <div class="dropdown-menu" aria-labelledby="dropdownLanguageMenu">
            <a class="dropdown-item" href="#">
              <div class="row no-gutters align-items-center flex-nowrap">
                <img class="flag" src="../assets/images/flags/us.png">
                <span class="px-3">English</span>
              </div>
            </a>
            <a class="dropdown-item" href="#">
              <div class="row no-gutters align-items-center flex-nowrap">
                <img class="flag" src="../assets/images/flags/ro.png">
                <span class="px-3">Romanian</span>
              </div>
            </a>
          </div>
        </div>
        <div class="toolbar-separator"></div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<aside id="aside" class="aside aside-left" data-fuse-bar="aside" data-fuse-bar-media-step="md" data-fuse-bar-position="left">
  <div class="aside-content bg-primary-700 text-auto">
    <div class="aside-toolbar">
      
    <%= link_to({:controller => :dashboard, :action => :index}) do %>
    <div class="logo">
      <%= image_tag("logo.png", :alt => "rss feed") %>
        <span style="color:white;" class="logo-text">Smart Spending & Saving</span>
      </div>
      <% end %>
      <button id="toggle-fold-aside-button" type="button" class="btn btn-icon d-none d-lg-block" data-fuse-aside-toggle-fold>
        <i class="icon icon-backburger"></i>
      </button>
    </div>
    <ul class="nav flex-column custom-scrollbar" id="sidenav" data-children=".nav-item">
      <li class="subheader">
        <span>YOUR MENU</span>
      </li>
      <li class="nav-item">

        <%= link_to({:controller => :expenses, :action => :index}, :class => "nav-link ripple") do %>
          <i class="icon s-4 fas fa-money-bill"></i>
          <span><%= t('expenses.this') %></span>
        <% end %>

      </li>
      <li class="nav-item">

        <%= link_to({:controller => :reports, :action => :index}, :class => "nav-link ripple") do %>
          <i class="icon s-4 fas fa-file-invoice"></i>
          <span><%= t('reports.this') %></span>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to({:controller => :tags, :action => :index}, :class => "nav-link ripple") do %>
          <i class="icon s-4 fas fa-tag"></i>

          <span>Tags</span>
        <% end %>
      </li>
    </ul>
  </div>
</aside>

app/views/layouts/_welcome.html.erb
<link rel="stylesheet" href="https://cdn.lineicons.com/1.0.0/LineIcons.min.css">
<link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.css" />

<div class="container-fluid bg">
  <div class="container custom-container-welcome">
    <div class="row">
      <div class="col-md-8 ">
        <div class="row">
          <div class="col-sm-3 col-md-2 col-lg-2">
            <i class="lni lni-enter" aria-hidden="true"></i>
          </div>
          <div class="col-sm-9 col-md-10 col-lg-10">
            <h1 class="heading"><%= t('home.register') %></h1>
          </div>
        </div>

        </br>
        </br>

        <div class="row">
          <div class="col-sm-3 col-md-2 col-lg-2">
            <i class="lni lni-user" aria-hidden="true"></i>
          </div>
          <div class="col-sm-9 col-md-10 col-lg-10">
            <h1 class="heading"><%= t('home.create_your_profile') %></h1>
          </div>
        </div>

        </br>
        </br>

        <div class="row">
          <div class="col-sm-3 col-md-2 col-lg-2">
            <i class="lni lni-cloud-upload" aria-hidden="true"></i>
          </div>
          <div class="col-sm-9 col-md-10 col-lg-10">
            <h1 class="heading"><%= t('home.upload_expenses') %></h1>
          </div>
        </div>

        </br>
        </br>

        <div class="row">
          <div class="col-sm-3 col-md-2 col-lg-2">
            <i class="lni lni-search" aria-hidden="true"></i>
          </div>
          <div class="col-sm-9 col-md-10 col-lg-10">
            <h1 class="heading"><%= t('home.manage_your_money') %></h1>
          </div>
        </div>

        </br>
        </br>
        </br>
        </br>

      </div>
      <div class="col-md-4 custom-card-welcome">
        <div class="card regform wow bounce animated" data-wow-delay="0.05s">
          <div class="card-body regform">
            <div class="myform form ">
              <div class="logo mb-3">
                <div class="col-md-12 text-center">
                  <h1 class="sign"><%= t('home.join') %></h1>
                </div>
              </div>

              <%= simple_form_for(:user, :url => registration_path(:user), :html => { :class => 'custom-form-welcome'}) do |f| %>
                <%= f.error_notification %>

                <div class="form-group">
                  <label for="email"><%= t('home.email_address') %></label>
                  <%= f.input_field :email,
                                    required: true,
                                    autofocus: true,
                                    input_html: { autocomplete: "email" },
                                    class: "form-control field-with-errors",
                                    label: false %>
                </div>

                <div class="form-group">
                  <label for="password"><%= t('home.password') %></label>
                  <%= f.input_field :password,
                                    required: true,
                                    hint: (t('devise.shared.minimum_password_length', count: @minimum_password_length) if @minimum_password_length),
                                    input_html: { autocomplete: "new-password" },
                                    class: "form-control field-with-errors",
                                    label: false %>
                </div>

                <div class="form-group">
                  <label for="email"><%= t('home.password_confirmation') %></label>
                  <%= f.input_field :password_confirmation,
                                    required: true,
                                    input_html: { autocomplete: "new-password" },
                                    class: "form-control field-with-errors",
                                    label: false %>
                </div>

                <div class="col-md-12 text-center mb-3">
                  <div class="form-group">
                    <%= f.button :submit, t('home.sign_up'), class: "btn btn-block mybtn btn-primary tx-tfm" %>
                  </div>
                </div>

              <% end %>

              <div class="col-md-12 ">
                <div class="form-group">
                  <p class="text-center">
                    <%= link_to t('home.already_have_an_account'), controller: "devise/sessions", action: "new" %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

    $("#signup").click(function () {
        $("#first").fadeOut("fast", function () {
            $("#second").fadeIn("fast");
        });
    });

    $("#signin").click(function () {
        $("#second").fadeOut("fast", function () {
            $("#first").fadeIn("fast");
        });
    });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smart Spending & Savings</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= yield :stylesheets %>
  <style type="text/css">
    [fuse-cloak],
    .fuse-cloak {
      display: none !important;
    }

    @font-face {
      font-family: 'fuse-iconfont';
      src: url('../assets/fonts/fuse-iconfont.ttf') format('truetype'),
      url('../assetsfonts/fuse-iconfont.woff') format('woff'),
      url('../assetsfonts/fuse-iconfont.svg') format('svg');
      font-weight: normal;
      font-style: normal;
    }
  </style>

  <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= yield :scripts %>

</head>

<body class="layout layout-vertical layout-left-navigation layout-above-toolbar layout-above-footer">

<%= yield %>

</body>
</html>